<a href="https://colab.research.google.com/github/cashby-890/ST-554-HW5/blob/main/ST554_Homework_Five_Cody_Ashby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ST 554 Spring 2026 Homework Five by Cody Ashby**

## ***Part I: Concepts of Big Data***

## ***Part II: Simulation of Sampling Distribution***

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## ***Part III: Examples of Big Data and Rare Events***

## ***Part IV: Querying a Database***

In [10]:
import sqlite3
con = sqlite3.connect("lahman_1871-2022.sqlite")

In [11]:
cursor = con.cursor()
get_schema='''
        select *
        from sqlite_schema
        where type="table";
        '''
cursor.execute(get_schema)
result=cursor.fetchall()
cursor.close()

In [12]:
lahman_df=pd.read_sql(get_schema,con)
lahman_df

,type,name,tbl_name,rootpage,sql
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

In [36]:
pd.read_sql("select * from Teams where yearID=2015;",con)

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,2015,AL,BAL,BAL,E,3,162,78,81,81,...,134,0.987,Baltimore Orioles,Oriole Park at Camden Yards,2281202,103,104,BAL,BAL,BAL
1,2015,AL,BOS,BOS,E,5,162,81,78,84,...,148,0.984,Boston Red Sox,Fenway Park II,2880694,104,107,BOS,BOS,BOS
2,2015,AL,CHA,CHW,C,4,162,81,76,86,...,159,0.983,Chicago White Sox,U.S. Cellular Field,1755810,92,93,CHW,CHA,CHA
3,2015,AL,CLE,CLE,C,3,161,80,81,80,...,136,0.987,Cleveland Indians,Progressive Field,1388905,106,106,CLE,CLE,CLE
4,2015,AL,DET,DET,C,5,161,81,74,87,...,165,0.986,Detroit Tigers,Comerica Park,2726048,97,98,DET,DET,DET
5,2015,AL,HOU,HOU,W,2,162,81,86,76,...,131,0.986,Houston Astros,Minute Maid Park,2153585,97,99,HOU,HOU,HOU
6,2015,AL,KCA,KCR,C,1,162,81,95,67,...,138,0.985,Kansas City Royals,Kauffman Stadium,2708549,104,103,KCR,KCA,KCA
7,2015,AL,LAA,ANA,W,3,162,81,85,77,...,108,0.984,Los Angeles Angels of Anaheim,Angel Stadium of Anaheim,3012765,94,95,LAA,ANA,ANA
8,2015,AL,MIN,MIN,C,2,162,81,83,79,...,150,0.986,Minnesota Twins,Target Field,2220054,103,104,MIN,MIN,MIN
9,2015,AL,NYA,NYY,E,2,162,81,87,75,...,135,0.985,New York Yankees,Yankee Stadium III,3193795,99,101,NYY,NYA,NYA
10,2015,AL,OAK,OAK,W,5,162,81,68,94,...,154,0.979,Oakland Athletics,O.co Coliseum,1768175,97,98,OAK,OAK,OAK
11,2015,AL,SEA,SEA,W,4,162,81,76,86,...,155,0.985,Seattle Mariners,Safeco Field,2193581,92,94,SEA,SEA,SEA
12,2015,AL,TBA,TBD,E,4,162,84,80,82,...,118,0.984,Tampa Bay Rays,Tropicana Field,1287054,100,102,TBR,TBA,TBA
13,2015,AL,TEX,TEX,W,1,162,81,88,74,...,169,0.981,Texas Rangers,Globe Life Park in Arlington,2491875,102,105,TEX,TEX,TEX
14,2015,AL,TOR,TOR,E,1,162,81,93,69,...,145,0.985,Toronto Blue Jays,Rogers Centre,2794891,99,98,TOR,TOR,TOR
15,2015,NL,ARI,ARI,W,3,162,81,79,83,...,146,0.986,Arizona Diamondbacks,Chase Field,2080145,107,106,ARI,ARI,ARI
16,2015,NL,ATL,ATL,E,4,162,81,67,95,...,186,0.985,Atlanta Braves,Turner Field,2001392,97,97,ATL,ATL,ATL
17,2015,NL,CHN,CHC,C,3,162,81,97,65,...,120,0.982,Chicago Cubs,Wrigley Field,2919122,100,100,CHC,CHN,CHN
18,2015,NL,CIN,CIN,C,5,162,81,64,98,...,131,0.985,Cincinnati Reds,Great American Ball Park,2419506,101,101,CIN,CIN,CIN
19,2015,NL,COL,COL,W,5,162,81,68,94,...,171,0.985,Colorado Rockies,Coors Field,2506789,119,118,COL,COL,COL
20,2015,NL,LAN,LAD,W,1,162,81,92,70,...,133,0.988,Los Angeles Dodgers,Dodger Stadium,3764815,101,98,LAD,LAN,LAN
21,2015,NL,MIA,FLA,E,3,162,81,71,91,...,162,0.987,Miami Marlins,Marlins Park,1752235,98,97,MIA,FLO,MIA
22,2015,NL,MIL,MIL,C,4,162,81,68,94,...,164,0.981,Milwaukee Brewers,Miller Park,2542558,101,101,MIL,ML4,MIL
23,2015,NL,NYN,NYM,E,1,162,81,90,72,...,131,0.986,New York Mets,Citi Field,2569753,94,92,NYM,NYN,NYN
24,2015,NL,PHI,PHI,E,5,162,81,63,99,...,145,0.981,Philadelphia Phillies,Citizens Bank Park,1831080,98,98,PHI,PHI,PHI
25,2015,NL,PIT,PIT,C,2,162,81,98,64,...,177,0.981,Pittsburgh Pirates,PNC Park,2498596,99,97,PIT,PIT,PIT
26,2015,NL,SDN,SDP,W,4,162,81,74,88,...,138,0.985,San Diego Padres,Petco Park,2459742,98,97,SDP,SDN,SDN
27,2015,NL,SFN,SFG,W,2,162,81,84,78,...,145,0.987,San Francisco Giants,AT&T Park,3375882,99,97,SFG,SFN,SFN
28,2015,NL,SLN,STL,C,1,162,81,100,62,...,159,0.984,St. Louis Cardinals,Busch Stadium III,3520889,102,101,STL,SLN,SLN
29,2015,NL,WAS,WSN,E,2,162,81,83,79,...,125,0.985,Washington Nationals,Nationals Park,2619843,102,99,WSN,MON,WAS

In [37]:
pd.read_sql("select playerID,yearid,inducted from HallOfFame where inducted='Y';",con)

      playerID  yearid inducted
0    aaronha01    1982        Y
1    alexape01    1938        Y
2    alomaro01    2011        Y
3    alstowa01    1983        Y
4    andersp01    2000        Y
..         ...     ...      ...
335  yastrca01    1989        Y
336  yawketo99    1980        Y
337  youngcy01    1937        Y
338  youngro01    1972        Y
339  yountro01    1999        Y

[340 rows x 3 columns]